complete -c tit -f
complete -c tit -l config -r -d 'Read configuration from a file'
complete -c tit -l user -d 'Read configuration from the XDG data directory'
complete -c tit -l public-url -r -d 'Override the canonical public URL'
complete -c tit -l http-listen -r -d 'Override the HTTP listener address'
complete -c tit -l ssh-listen -r -d 'Override the SSH listener address'
complete -c tit -l ssh-public-host -r -d 'Override the advertised SSH hostname'
complete -c tit -l ssh-public-port -r -d 'Override the public SSH port'
complete -c tit -s h -l help -d 'Print help'
complete -c tit -s V -l version -d 'Print the version'
complete -c tit -n '__fish_use_subcommand' -a serve -d 'Start the HTTP and SSH servers'
complete -c tit -n '__fish_use_subcommand' -a invite-code -d 'Create a single-use signup invitation'
complete -c tit -n '__fish_use_subcommand' -a doctor -d 'Check the instance without changing it'
complete -c tit -n '__fish_use_subcommand' -a inspect -d 'Show one typed instance record as JSON'
complete -c tit -n '__fish_use_subcommand' -a dump -d 'Write all SQLite rows as deterministic JSON Lines'
complete -c tit -n '__fish_use_subcommand' -a repair -d 'Run an explicit repair operation'
complete -c tit -n '__fish_use_subcommand' -a backup -d 'Create a backup archive'
complete -c tit -n '__fish_use_subcommand' -a restore -d 'Restore a backup archive'
complete -c tit -n '__fish_use_subcommand' -a setup -d 'Set up an uninitialized instance'
complete -c tit -n '__fish_use_subcommand' -a admin -d 'Run an offline administrator command'
