#!/bin/sh
set -eu

cargo fmt --check
cargo clippy --all-targets --all-features -- -D warnings
cargo test --locked --all-targets --all-features
cargo deny check advisories licenses sources
cargo build --locked --release
