#!/bin/sh
set -eu

./scripts/check
cargo test --locked --release --test git_reads measures_bounded_search_without_an_index -- --ignored --nocapture
cargo test --locked --release --test public_routes browses_and_clones_public_repositories_for_both_hash_formats
