#!/bin/sh
set -eu

./scripts/check
cargo test --locked --release --test sqlite
cargo test --locked --release --test public_routes browses_and_clones_public_repositories_for_both_hash_formats
cargo test --locked --release --test git_push_ssh reconciles_process_termination_at_each_cross_store_boundary
