#!/bin/sh
set -eu

./scripts/check
cargo test --locked --release --bin tit parses_only_bounded_pull_request_checkout_commands
cargo test --locked --release --test serve creates_owned_repositories_with_stable_ssh_command_output
